version: '3.4'

services:
  goodtowork.tasksorganizer.api:
    image: ${DOCKER_REGISTRY-}goodtoworktasksorganizerapi
    build:
      context: .
      dockerfile: GoodToWork.TasksOrganizer.API/Dockerfile
    ports:
      - 444:443

  goodtowork.notificationservice.api:
    image: ${DOCKER_REGISTRY-}goodtoworknotificationserviceapi
    build:
      context: .
      dockerfile: GoodToWork.NotificationService.API/Dockerfile
    ports:
      - 448:443

  messages:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    hostname: "rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmquser
      - RABBITMQ_DEFAULT_PASS=rabbitmqPasswork12!
  
  tasksorganizerdatabase:
    container_name: "tasksOrganizer-db-sql"
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "password123"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    volumes:
      - C:\\Data\\DockerVloumes\\GoodToWork\\TasksOrganizer:/var/opt/mssql/data

  notificationdatabase:
    image: mongo:latest
    container_name: "notificationdatabase-mongodb"
    ports:
      - 27014:27017
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://root:password123@mongo:27014/
    volumes:
      - C:\\Data\\DockerVloumes\\GoodToWork\\Notification:/data/db